# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Connect-SmartDock-SEAsia'
    subscriptionId: '76f3aed9-0e71-4d66-8034-168fd25cb2e9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG-SmartDock-SEAsia'
    location: 'Southeast Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-storage-account-create/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate_01'
